# Generated by Django 5.0.2 on 2024-08-06 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantedtree",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trees.account",
            ),
        ),
    ]
